flake.nix: init
NixOS/nixpkgs-vet pull request #65
Opened 2024-05-14 18:32 UTC by philiptaron

I like flakes. 🤷🏻‍♂️ 

* Added `flake.nix`
  * Wired up the package to the default build output for `nix build`
  * Wired up the shell to the default shell for `nix shell`
  * Wired up the two checks (for formatting and nixpkgs) to `nix flake check`.
  * Added the hydra-built systems as the default systems
* Added `nix flake update` to the update scripts
* Reshaped `default.nix` to accept `pkgs` as an input
* Added `treefmtWrapper` (per the docs on [treefmt-nix](https://github.com/numtide/treefmt-nix?tab=readme-ov-file#flakes)) that fits into `nix fmt`.

2024-05-14 18:46 UTC, philiptaron commented
Turns out that `nix flake update` is failing in the CI scripts. I wonder if it's a "nix from inside nix" problem. There's no output, which is sad.

2024-05-14 21:41 UTC, infinisil requested changes
I'm not against having a flake.nix in principle, but this currently duplicates all the input locking! And I'd rather not use flake inputs because then they can't be overridden by stable Nix (unless you [implement it manually](https://github.com/edolstra/flake-compat/pull/49)).

So `flake.nix` should just be a tiny layer above `default.nix`, like [the one in nixfmt](https://github.com/NixOS/nixfmt/blob/master/flake.nix).

2024-05-14 21:52 UTC, philiptaron commented
@infinisil, it _is_ a tiny layer above `default.nix`! I did it differently than the nixfmt one because the Nix code is shaped differently, but there's no getting around the flake's use of flake.lock. I thought the simplest way to go was duplication rather than trying to make `npins` flake compatible.

2024-05-14 22:22 UTC, infinisil commented
> there's no getting around the flake's use of flake.lock

There is though! If you just don't specify any flake inputs and instead import the `default.nix` (which then uses the niv-pinned ones) with its default arguments, it should work just fine

2024-05-14 22:49 UTC, philiptaron commented
> if you don't specify flake inputs

But that's what I want the flake _for_ -- specifying inputs. Without any inputs, as a flake consumer, I have to use whatever's pinned, and there's no ability to override.

I think the right way to go is to update npins to 0.2.4 (per the linked review), then use the [import-flake](https://github.com/andir/npins/pull/70) to base the npins off flake.lock.

2024-05-14 22:59 UTC, willbush commented
Would `.envrc` be `use flake` or `use nix`?

2024-05-14 23:07 UTC, philiptaron commented
> Would `.envrc` be `use flake` or `use nix`?

It would be able to contain `use flake` should this PR be merged.

2024-05-14 23:40 UTC, infinisil commented
> Without any inputs, as a flake consumer, I have to use whatever's pinned, and there's no ability to override.

You can override the pinned sources using the `default.nix`. E.g.

```nix
{
  inputs.ncbn.url = "github:NixOS/nixpkgs-check-by-name";
  inputs.ncbn.flake = false;

  outputs = { ncbn, ... }:
    let
      result = import ncbn {
        nixpkgs = <something else>;
      };
    in
    {
      packages.ncbn = result.build;
    };
}
```

This notably has the advantage that you can even override it with a version of Nixpkgs that Flake inputs can't represent, e.g. one patched via a derivation, or fetched with a non-builtin fetcher, etc.

2024-05-19 01:14 UTC, willbush commented
Feel like I don't know enough about the pros/cons of flakes despite using them for like 4 years.

I think at a minimum we shouldn't have two lock files for the same inputs.

Is there any tradeoff in evaluation caching between using flakes vs npins lock file?

2024-05-31 18:02 UTC, philiptaron commented
I'm returning to this PR after a couple weeks, but I'm going to be experimenting with how GitHub actions runs the code a bit so please bear it no mind until it's out of draft.

2024-10-23 07:31 UTC, willbush commented
> > Would `.envrc` be `use flake` or `use nix`?
> 
> It would be able to contain `use flake` should this PR be merged.

I noticed [this](https://github.com/helix-editor/helix/blob/6d64e6288add793caf1c841ea295518414c04ea0/.envrc#L6) recently `use flake || use nix`.

2024-11-29 19:37 UTC, closed without merging